apiVersion: v2
appVersion: '1.0'
description: A Helm chart for fis-ds-update-web App
name: fis-ds-update-web
home: https://github.com/hmcts/fis-ds-update-web
version: 0.0.10
dependencies:
  - name: nodejs
    version: 3.1.0
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
